// Keeps package.json's "sideEffects" array in sync with the shared chunk
// files that esbuild/tsup emits when code splitting is enabled.
//
// Why this is needed: string.ts/number.ts/array.ts/full.ts/coerce.ts each
// call `extend()` at module top-level to register extension methods (e.g.
// `toLowerCase()`) onto the shared schema interfaces. When two or more entry
// points share this code (e.g. full.ts re-exports string/number/array), tsup
// splits it out into a separate `dist/chunk-<hash>.mjs` file that is
// imported purely for its side effect. Since these chunk file names are
// content-hashed, they can't be hardcoded in package.json's `sideEffects`
// array (they change on every build). Bundlers that respect `sideEffects`
// (webpack, Rollup, etc.) could otherwise tree-shake away that import and
// silently drop the extension methods.
//
// This script runs after `tsup` as part of `npm run build` and rewrites the
// `./dist/chunk-*` entries in `sideEffects` to match whatever chunk files
// were actually generated by the current build.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(fileURLToPath(import.meta.url), '../..');
const distDir = path.join(rootDir, 'dist');
const pkgPath = path.join(rootDir, 'package.json');

const chunkFiles = readdirSync(distDir)
  .filter((file) => /^chunk-.*\.(mjs|cjs)$/.test(file))
  .sort()
  .map((file) => `./dist/${file}`);

const pkgRaw = readFileSync(pkgPath, 'utf8');
const pkg = JSON.parse(pkgRaw);

const nonChunkSideEffects = (pkg.sideEffects ?? []).filter(
  (entry) => !entry.startsWith('./dist/chunk-'),
);

pkg.sideEffects = [...nonChunkSideEffects, ...chunkFiles];

// Preserve the file's existing indentation/newline style as closely as possible.
const trailingNewline = pkgRaw.endsWith('\n') ? '\n' : '';
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}${trailingNewline}`);

console.log(
  `Synced ${chunkFiles.length} chunk file(s) into package.json sideEffects.`,
);
